Repository hyochan/react-native-iap, pull requests merged in 2019-08, with the labels that each got.

#625 Release 3.3.8
  CHANGELOG.md
  android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
  package.json
  yarn.lock
Labels: release

#616 Supported old error codes
  IapExample/ios/Podfile.lock
  android/src/main/java/com/dooboolab/RNIap/DoobooUtils.java
  android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
  ios/RNIap.xcodeproj/project.pbxproj
  ios/RNIap.xcodeproj/xcshareddata/xcschemes/RNIap.xcscheme
  ios/RNIapIos.m
Labels: android, enhancement, iOS

#628 Release 3.3.9
  CHANGELOG.md
  package.json
Labels: release

#650 fix: make it build with older XCode
  ios/RNIapIos.m
Labels: enhancement

#654 fix(getSubscriptions) : iOS return subs properly
  index.js
Labels: enhancement, iOS

#663 method to retrieve pending transactions
  README.md
  index.d.ts
  index.js
  ios/RNIapIos.m
Labels: enhancement, feature
