Repository hyochan/react-native-iap, pull requests merged in 2019-06, with the labels that each got.

#507 Update README.md
  README.md
Labels: doc

#524 Remove deprecated annotation on requestSubscription method in index.d.ts
  index.d.ts
Labels: types

#529 fixed typo in TypeScript definition file
  index.d.ts
Labels: types

#521 Improved handling of receipts
  README.md
  index.d.ts
  index.js
  ios/RNIapIos.m
Labels: feature

#533 Updated method name in readme
  README.md
Labels: doc

#534 Handle better message for issue like #515
  android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
  package.json
Labels: enhancement

#535 Fix purchases.size
  android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
Labels: bugfix

#537 Fixes #530 enhanced
  IapExample/App.js
  android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
  index.js
  package.json
Labels: bugfix

#539 Make ensureConnection always provide a valid BillingClient
  android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
Labels: android, enhancement

#551 Fixes #546
  CHANGELOG.md
  android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
  package.json
Labels: bugfix

#552 Fix transactionId for google
  android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
Labels: android, bugfix, enhancement

#553 Release 3.1.1
  CHANGELOG.md
  package.json
Labels: release

#558 Update readme
  CHANGELOG.md
  README.md
  package.json
Labels: release

#559 Release 3.2.2
  CHANGELOG.md
  IapExample/App.js
  README.md
  index.d.ts
  index.js.flow
  package.json
Labels: release

#560 Update acknowledgePurchaseAndroid() example
  IapExample/App.js
  README.md
Labels: doc, example

#564 Closes #563 and release 3.2.3
  index.js.flow
  package.json
Labels: release, types, typo

#543 Fix typo in README
  README.md
  README_DEPRECATED.md
Labels: doc, typo

#574 Improve README
  README.md
Labels: doc
