Repository hyochan/react-native-iap, pull requests merged in 2019-05, with the labels that each got.

#472 Remove comments about ejected apps in README
  README.md
Labels: doc

#475 Updated README.md about potential Q&A issue
  README.md
Labels: doc

#477 Typo in README (invetory)
  README.md
Labels: doc

#482 Fix flow typing
  index.js.flow
Labels: types

#488 Update Gradle 3.2.1 - build tools version 28.0.3
  android/build.gradle
Labels: android, build

#489 Fix gradle api usage
  android/build.gradle
Labels: android, build

#490 Fix promo code purchase not being restored.
  ios/RNIapIos.m
Labels: bugfix

#493 Fix Platform Specific Type Definitions
  index.d.ts
Labels: types

#500 add tvos as build target
  ios/RNIap.xcodeproj/project.pbxproj
Labels: feature

#505 update Readme
  README.md
Labels: doc
