Repository hyochan/react-native-iap, pull requests merged in 2019-11, with the labels that each got.

#833 Enhanced `finishTransaction` method to be more useful
  CHANGELOG.md
  IapExample/App.js
  README.md
  index.ts
  package.json
Labels: enhancement, release

#835 Fix Android compile error for React Native v0.60.x due to missing method
  android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
Labels: bugfix

#840 README: add finishTransaction() method description
  README.md
Labels: doc

#854 Fix some warnings and a bug
  .npmignore
  ios/RNIapIos.m
Labels: bugfix, enhancement

#857 Remove duplicate (and dated) requestSubscription entry from README
  README.md
Labels: doc
