Repository hyochan/react-native-iap, pull requests merged in 2019-10, with the labels that each got.

#746 Return correct Subscription[] type for getSubscriptions
  index.ts
Labels: bugfix, types

#749 Resolve #748
  CHANGELOG.md
  android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
  package.json
Labels: bugfix, release

#754 Add example backend link
  README.md
Labels: doc

#752 Typings: Move isAcknowledgedAndroid to ProductPurchase
  index.ts
Labels: enhancement, lint

#759 fix(validateReceiptAndroid): template literals properly
  .npmignore
  CHANGELOG.md
  index.ts
  package.json
Labels: bugfix, release

#716 Release preview for 4.0.0+
  .gitignore
  CHANGELOG.md
  IapExample/App.js
  IapExample/package.json
  IapExample/yarn.lock
  README.md
  android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
  index.ts
  ios/RNIapIos.m
  package.json
  yarn.lock
Labels: preview, release

#768 release/4.0.1
  CHANGELOG.md
  android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
  package.json
Labels: bugfix, release

#774 Release 4.0.3
  android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
  package.json
Labels: bugfix, release

#781 Release 4.0.4
  CHANGELOG.md
  README.md
  package.json
Labels: release

#806 [Android] Fixed promise never returned from requestSubscription()
  android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
Labels: enhancement

#807 [Android] added subs to the list of unconsumed purchases
  android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
Labels: enhancement

#809 [iOS] Fixed promise acceptation/rejection not propagated to JS
  ios/RNIapIos.m
Labels: enhancement

#812 Release/4.0.8
  CHANGELOG.md
  package.json
Labels: release
