Repository hyochan/react-native-iap, pull requests merged in 2019-07, with the labels that each got.

#578 Fixes #577
  CHANGELOG.md
  ios/RNIapIos.m
  package.json
Labels: build, iOS

#586 Update index.js.flow
  index.js.flow
Labels: types

#589 Fix #581 finishTransaction called automatically
  CHANGELOG.md
  IapExample/ios/Podfile.lock
  IapExample/metro.config.js
  IapExample/package.json
  README.md
  android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
  docs/react-native-iapv3.svg
  index.js
  ios/RNIapIos.m
  package.json
Labels: enhancement, feature, working

#595 Upgrade example project rn version
  IapExample/ios/Podfile.lock
  IapExample/package.json
  IapExample/yarn.lock
Labels: upgrade

#594 Fix flow type for purchaseUpdatedListener
  index.js.flow
Labels: types

#596 Release 3.3.1
  .travis.yml
  CHANGELOG.md
  index.js
  package.json
  tsconfig.json
  yarn.lock
Labels: types

#599 [3.3.2] Added missing types on updates in 3.3.0
  index.d.ts
  index.js.flow
  package.json
Labels: release, types

#602 Keep valid SKUs in memory
  android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
Labels: bugfix, enhancement

#607 Check billingClient before invoking callback
  android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
Labels: android, enhancement

#608 Release 3.3.6
  CHANGELOG.md
  package.json
Labels: release

#613 Avoid looping on a null purchases list
  android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
Labels: bugfix
