Repository hyochan/react-native-iap, pull requests merged in 2019-09, with the labels that each got.

#680 Destroying listeners in proper React's life cycle method
  IapExample/App.js
Labels: correction, example

#683 Add more types to acknowledgePurchaseAndroid response
  index.d.ts
Labels: android, types

#684 Make all SubscriptionPurchase property types optional, as they are different per platform
  index.d.ts
Labels: iOS, types

#685 README update: consumePurchaseAndroid is "Android only"
  README.md
Labels: android, doc

#687 Update readme to include a section about cancelling subscriptions
  README.md
Labels: doc

#681 transactionDate is received as a string, not a number
  android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
Labels: types

#696 Add discounts array to Subscription type (iOS Only)
  index.d.ts
Labels: iOS, types

#703 release/3.4.5
  CHANGELOG.md
  README.md
  android/build.gradle
  index.js.flow
  package.json
Labels: doc, migration, release

#704 fix: fix unresolved promise in initConnection
  android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
Labels: enhancement

#713 Update package to 3.4.7
  CHANGELOG.md
  android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
  index.d.ts
  index.js.flow
  package.json
Labels: android, release

#714 feat: improve initConnection errors on android
  android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
Labels: enhancement

#718 feat: expose error codes
  index.d.ts
  index.js
  index.js.flow
Labels: feature, types

#737 fix: interface "ID" extending a primitive type
  index.d.ts
Labels: types

#738 Add missing fields to PurchaseResult & PurchaseError
  index.js.flow
Labels: types

#739 Release 3.5.0
  .eslintrc.js
  .gitignore
  .npmignore
  .travis.yml
  CHANGELOG.md
  IapExample/App.js
  IapExample/ios/Podfile.lock
  IapExample/metro.config.js
  IapExample/yarn.lock
  android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
  index.d.ts
  index.js.flow
  index.ts
  package.json
  tsconfig.json
  type/apple.d.ts
  yarn.lock
Labels: android, release, types
