Repository hyochan/react-native-iap, pull requests merged in 2019-01, with the labels that each got.

#372 Update README.md
  README.md
Labels: doc

#379 Fix for BillingClientImpl Crashes - Promise consumed twice
  android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
Labels: android, bugfix

#363 fix example to correctly display available purchases
  RNIapExample/src/components/pages/First.js
Labels: doc

#388 Add support for iOS In-App Purchase promotions
  README.md
  index.js
  ios/RNIapIos.m
Labels: feature
