Repository hyochan/react-native-iap, pull requests merged in 2020-10, with the labels that each got.

#1141 return ability to set 'obfuscatedAccountId' and 'obfuscatedProfileId' for android billing v3
  README.md
  android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
  index.ts
Labels: enhancement, hacktoberfest-accepted

#1149 Fix amazon buyItemByType missing parameters
  android/src/main/java/com/dooboolab/RNIap/RNIapAmazonModule.java
Labels: bugfix, release

#1161 Update README.md
  README.md
Labels: doc

#1171 Expose more android variables on requests
  CHANGELOG.md
  IapExample/package.json
  IapExample/yarn.lock
  README.md
  android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
  package.json
Labels: android

#1173 fix(README): "Configure android sandbox" link was wrong
  README.md
Labels: doc
