Repository hyochan/react-native-iap, pull requests merged in 2020-09, with the labels that each got.

#1101 test: Be more specific in purchaseErrorListener param typing
  index.ts
Labels: types

#1112 Upgrade android billing sdk to v3
  CHANGELOG.md
  IapExample/ios/Podfile.lock
  README.md
  android/build.gradle
  android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
  index.ts
  package.json
Labels: android, upgrade

#1115 fix: Xcode 12 compatibility
  RNIap.podspec
Labels: bugfix, migration

#1124 Adding JavaVersion on build.gradle to work with Detox tests
  android/build.gradle
Labels: compatibility

#1129 Fix changing subscriptions on Android
  README.md
  android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
  index.ts
Labels: migration, regression
