Repository hyochan/react-native-iap, pull requests merged in 2020-11, with the labels that each got.

#1182 Add introductory price as string without formating and currency
  README.md
  index.ts
  ios/RNIapIos.m
Labels: enhancement

#1186 Add iOS store country code
  README.md
  index.ts
  ios/RNIapIos.m
Labels: feature

#1191 Fixed Amazon products prices parsing
  README_AMAZON.md
  android/gradle/wrapper/gradle-wrapper.properties
  android/src/main/java/com/dooboolab/RNIap/RNIapAmazonListener.java
Labels: android, bugfix
