Repository hyochan/react-native-iap, pull requests merged in 2021-10, with the labels that each got.

#1521 fix countryCode typing in ProductCommon interface
  src/types/index.ts
Labels: ❄️ types

#1523 fix(docs): Wrong import in hooks documentation
  docs/docs/usage_instructions/using_hooks.md
Labels: 📖 documentation

#1522 Update .npmignore to remove TS errors
  .npmignore
Labels: 👷‍♀️ build
