Repository hyochan/react-native-iap, pull requests merged in 2021-08, with the labels that each got.

#1443 code cleanup
  CHANGELOG.md
  README_DEPRECATED.md
  android/src/amazon/java/com/dooboolab/RNIap/RNIapAmazonModule.java
  android/src/play/java/com/dooboolab/RNIap/RNIapModule.java
  docs/docs/amazon.md
  docs/docs/api_reference/methods.md
  docs/docs/support_us.md
  docs/docs/usage_instructions/purchase.md
  docs/docs/usage_instructions/receipt_validation.md
  ios/RNIapIos.m
  src/iap.ts
Labels: 🛠 refactor

#1447 Fix crash when init on Android Emulator
  android/src/play/java/com/dooboolab/RNIap/RNIapModule.java
Labels: 🍗 enhancement, 🤖 android

#1452 Fix crash on android requestPurchase
  src/iap.ts
Labels: 🤖 android, 🔥 hotfix

#1444 Added monolinter and fixed inconsistent dependency versions
  .monolinterrc
  IapExample/android/build.gradle
  IapExample/package.json
  IapExample/yarn.lock
  docs/docs/installing.md
  docs/package.json
  package.json
  yarn.lock
Labels: 💨 ci, dependencies

#1456 Fix android crash by delaying ios check
  src/iap.ts
Labels: 🔥 hotfix

#1461 improve receipt types
  CHANGELOG.md
  IapExample/package.json
  IapExample/yarn.lock
  android/src/amazon/java/com/dooboolab/RNIap/RNIapAmazonListener.java
  src/iap.ts
  src/types/index.ts
  yarn.lock
Labels: ❄️ types

#1465 migrated IapExample iOS to rn 0.64
  IapExample/App.js
  IapExample/ios/IapExample.xcodeproj/project.pbxproj
  IapExample/ios/Podfile
  IapExample/ios/Podfile.lock
  IapExample/package.json
  IapExample/yarn.lock
  ios/RNIap.xcodeproj/project.pbxproj
  ios/RNIapIos.swift
Labels: 🚽 migration, 📗 example

#1471 Fix table display in the document
  docs/docs/api_reference/methods.md
Labels: 📖 documentation
