Repository hyochan/react-native-iap, pull requests merged in 2021-09, with the labels that each got.

#1482 Use React's Context to manage IAP state
  README.md
  docs/docs/usage_instructions/using_hooks.md
  src/hooks/useIAP.ts
  src/hooks/withIAPContext.tsx
  src/index.ts
  tsconfig.json
Labels: 🍗 enhancement

#1476 Add quantity in purchase data
  docs/docs/api_reference/available_purchase.md
  ios/RNIapIos.m
  src/types/index.ts
Labels: 🍗 enhancement, 🛠 bugfix

#1491 Fix typos found in docs and README.md
  README.md
  docs/docs/amazon.md
  docs/docs/faq.md
  docs/docs/usage_instructions/purchase.md
Labels: 📖 documentation

#1497 fix(docs): Return type of getPurchaseHistory wrong
  docs/docs/api_reference/methods.md
Labels: 📖 documentation

#1505 Setting default AndroidX version
  android/build.gradle
Labels: 🤖 android, 👷‍♀️ build

#1504 fix: Cancellled purchase kept promise dangling
  android/src/play/java/com/dooboolab/RNIap/RNIapModule.java
  ios/RNIapIos.m
Labels: 🍗 enhancement, 🛠 bugfix

#1506 Update packages
  IapExample/package.json
  IapExample/yarn.lock
  package.json
  yarn.lock
Labels: dependencies

#1520 fix possible typo "requesSubscription" in hooks
  src/hooks/useIAP.ts
Labels: 🥢 typo
