Repository hyochan/react-native-iap, pull requests merged in 2022-08, with the labels that each got.

#1782 Fix mismatch between buyProduct signatues in Obj-C and swift
  ios/RNIapIos.m
Labels: 📱 iOS, 🛠 bugfix, 📦 next

#1813 fix: make all types optional for requestPurchase
  IapExample/src/App.tsx
  src/types/index.ts
Labels: 🍗 enhancement, ❄️ types

#1819 ci: remove example proj on release
  .github/workflows/publish-package.yml
Labels: 💨 ci

#1820 ci: fix publishing workflow by removing example project
  .github/workflows/publish-next.yml
Labels: 🛠 bugfix, 💨 ci

#1847 fix: export modules through destructured import
  src/index.ts
Labels: 🛠 bugfix

#1853 chore: lean npm package
  package.json
  src/__tests__/iap.test.ts
Labels: 👷‍♀️ build

#1873 refactor!: make all methods take an object of params
  IapExample/src/screens/ClassSetup.tsx
  IapExample/src/screens/Products.tsx
  IapExample/src/screens/Subscriptions.tsx
  src/hooks/useIAP.ts
  src/hooks/withIAPContext.tsx
  src/iap.ts
  src/types/index.ts
Labels: 🛠 refactor, ⚡️ breaking
