Repository hyochan/react-native-iap, pull requests merged in 2024-01, with the labels that each got.

#2664 feat: Added export finishTransaction() from StoreKit2.
  src/modules/iosSk2.ts
Labels: 🎯 feature

#2669 fix: avoid app crash due to multiple reject invocation
  ios/RNIapIosSk2.swift
Labels: 📱 iOS, 🛠 bugfix

#2673 docs: typos
  docs/docs/migrate_to_11.0.0.mdx
Labels: 📖 documentation
