Repository hyochan/react-native-iap, pull requests merged in 2024-09, with the labels that each got.

#2833 Add instructions for using as an Expo package to get-started.mdx.
  docs/docs/get-started.mdx
Labels: 📖 documentation

#2839 Update eventEmitter.ts
  .github/workflows/ci-example-ios.yml
  ios/IapSerializationUtils.swift
  ios/RNIapIos.swift
  ios/RNIapIosSk2.swift
  package.json
  src/eventEmitter.ts
Labels: 🛠 refactor

#2845 Update purchases.mdx
  docs/docs/guides/purchases.mdx
Labels: 📖 documentation

#2848 feat: Upgrade Amazon's SDK to 3.0.5
  android/gradle.properties
Labels: 🤖 android, ⓐ amazon

#2850 Add conditional macro to omit confirmIn argument for Swift versions below 5.9
  ios/RNIapIosSk2.swift
Labels: 📱 iOS, 🛠 bugfix
