Repository hyochan/react-native-iap, pull requests merged in 2024-06, with the labels that each got.

#2758 chore: update expo config plugin for SDK 51
  package.json
  yarn.lock
Labels: 🚽 migration, dependencies

#2759 Update troubleshooting.mdx
  docs/docs/guides/troubleshooting.mdx
Labels: 📖 documentation

#2768 chore: migrate expo config plugins
  CONTRIBUTING.md
  IapExample/README.md
  IapExample/ios/Podfile.lock
  IapExample/yarn.lock
  README.md
  docs/docs/api-reference/hooks.md
  docs/src/pages/index.js
  docs/src/uis/AdFit.js
  docs/src/uis/AdFitTopFixed.js
  package.json
  plugin/__tests__/withIAP-test.ts
  plugin/build/withIAP.d.ts
  plugin/build/withIAP.js
  plugin/src/withIAP.ts
  src/eventEmitter.ts
  src/modules/iosSk2.ts
  yarn.lock
Labels: 🚽 migration

#2783 fix: latest promise crash on StoreKit 1
  ios/LatestPromiseKeeper.swift
Labels: 📱 iOS, 🛠 bugfix
