Repository hyochan/react-native-iap, pull requests merged in 2024-03, with the labels that each got.

#2687 Update hooks.md documentation
  docs/docs/api-reference/hooks.md
Labels: 📖 documentation

#2692 docs: Improving IapExample Readme.md
  IapExample/README.md
Labels: 📖 documentation

#2695 chore: Update Expo Config Plugins
  IapExample/ios/Podfile.lock
  IapExample/yarn.lock
  package.json
  yarn.lock
Labels: dependencies, 🗒️ chore

#2702 Update get-started.mdx to avoid crashing when app launching on iOS 12
  docs/docs/get-started.mdx
Labels: 📱 iOS, 📖 documentation
