Repository hyochan/react-native-iap, pull requests merged in 2025-09, with the labels that each got.

#2990 fix: fetch missing products from StoreKit when not cached
  CHANGELOG.md
  docs/blog/2025-09-08-release-14.1.1.md
  docs/blog/release-14-1-1.md
  example/ios/Podfile.lock
  ios/HybridRnIap.swift
  package.json
Labels: 🍗 enhancement

#2999 chore(android): bump OpenIAP Google to 1.1.0 and align init behavior
  README.md
  android/build.gradle
  android/src/main/java/com/margelo/nitro/iap/HybridRnIap.kt
  example/ios/Podfile.lock
  ios/HybridRnIap.swift
  plugin/__tests__/withIAP-android.test.ts
  plugin/src/withIAP.ts
  src/__tests__/index.test.ts
  src/index.ts
  src/specs/RnIap.nitro.ts
Labels: 🤖 android, 🛠 bugfix, 🚽 migration, 🛠 refactor

#3010 chore: align openiap deps
  NitroIap.podspec
  README.md
  android/build.gradle
  android/src/main/java/com/margelo/nitro/iap/HybridRnIap.kt
  example/ios/Podfile
  example/ios/Podfile.lock
  ios/HybridRnIap.swift
  plugin/__tests__/withIAP-android.test.ts
  plugin/src/withIAP.ts
Labels: dependencies, 💲 openiap

#3012 refactor!: streamline useIAP purchase handling
  CHANGELOG.md
  CLAUDE.md
  example/jest.setup.js
  src/__tests__/hooks/useIAP.test.ts
  src/hooks/useIAP.ts
Labels: 🛠 refactor

#3011 [docs] Update server-side validation library links in lifecycle guide
  docs/docs/guides/lifecycle.md
Labels: 📖 documentation

#3022 Add support for "auto-renewable-subscription" in iOS product type normalization
  src/utils/type-bridge.ts
Labels: ❄️ types

#3039 feat(enh): only include obfuscatedProfileIdAndroid for new purchase
  docs/docs/api/methods/listeners.md
  docs/docs/api/use-iap.md
  docs/docs/examples/available-purchases.md
  docs/docs/examples/offer-code.md
  docs/docs/examples/purchase-flow.md
  docs/docs/examples/subscription-flow.md
  docs/docs/guides/purchases.md
  docs/docs/guides/troubleshooting.md
  docs/docs/intro.md
  example/__tests__/screens/SubscriptionFlow.test.tsx
  example/ios/Podfile.lock
  example/screens/SubscriptionFlow.tsx
  example/src/utils/constants.ts
  openiap-versions.json
Labels: 🍗 enhancement, 🤖 android
